package rules

import parser.DataObject;
import parser.ActionObject;
import parser.DataObjectCollectionArrayList;

rule "Extinguishing Method"
salience -1
	when
		dataObjectCol : DataObjectCollectionArrayList()
				 
		dataObject : ActionObject(name == "ExtinguishingMethod") from dataObjectCol.getCollection()
		eval(dataObject != null && dataObject.hasField("FireExtinguishingMethod") && dataObject.getField("FireExtinguishingMethod").equals("Pool Use"))

	then
	
		System.out.println("The pool was used to extinguish the fire!");
end
