package rules

import parser.DataObject;
import parser.ActionObject;
import parser.DataObjectCollectionArrayList;
import java.util.HashMap;

rule "myTestRule"
	when
		dataObjectCol : DataObjectCollectionArrayList()
		dataObject1 : DataObject(name == "PoolLog") from dataObjectCol.getCollection() 
		 eval(dataObject1 != null&&dataObject1.getFieldInt("Temperature")>25)
	then
		 System.out.println("the Rule Builder Worked!");
end
