package rules

import parser.DataObject;
import parser.DataObjectCollectionArrayList;

rule "Pool Temp 5000"
	when
		dataObjectCol : DataObjectCollectionArrayList()
		dataObject : DataObject(name == "PoolLog") from dataObjectCol.getCollection()
		eval(dataObject != null && dataObject.hasField("Temperature") && dataObject.getFieldInt("Temperature") < 14)
	then
		//System.out.println("Water Too Cold!" + 14);

end