package rules

import parser.DataObject;

rule "Start Fire Alarm"
	when
		dataObject : DataObject()
		eval(dataObject.getField("Manual Fire Alarm Activation").equals("1")||dataObject.getField("Heat Detector").equals("1")&&dataObject.getField(" Smoke Detector").equals("1"))
	then
		 System.out.println("At time: "+ dataObject.getField("Time").toString() + " ~ Fire Alarm Activated!!!");
end
rule "Check Power"
	when
		dataObject : DataObject()
		eval(dataObject.getFieldInt("Primary Power Supply") < 50)
	then
		System.out.println("At time: "+ dataObject.getField("Time").toString() + " ~ Main Power Low!!!");
end
