package rules

import parser.DataObject;

rule "Start Fire Alarm"
	when
		dataObject : DataObject()
		eval(dataObject.hasField("Manual Fire Alarm Activation"))
		eval(dataObject.hasField("Heat Detector"))
		eval(dataObject.hasField("Heat Detector"))
		eval(dataObject.hasField("Smoke Detector"))
		eval(dataObject.getField("Manual Fire Alarm Activation").equals("1")||dataObject.getField("Heat Detector").equals("1")&&dataObject.getField("Smoke Detector").equals("1"))
	then
		 System.out.println("At time: "+ dataObject.getField("Time").toString() + " ~ Fire Alarm Activated!!!");
end
/*
rule "Check Power"
	when
		dataObject : DataObject()
		eval(dataObject.hasField("Primary Power Supply")&&dataObject.hasField("Time")&&dataObject.getFieldInt("Primary Power Supply") < 50)
	then
		System.out.println("At time: "+ dataObject.getField("Time").toString() + " ~ Main Power Low!!!");
end
*/