package rules

import parser.DataObject;
import parser.DataObjectCollection;

rule "erun"
	when
		dataObjectCol : DataObjectCollection()
		dataObject : DataObject() from dataObjectCol.getObject("FireAlarmSystem")
		eval(dataObject!=null&&dataObject.getField("Manual Fire Alarm Activation").equals("1")||dataObject.getField("Heat Detector").equals("1")&&dataObject.getField("Smoke Detector").equals("1"))
	then
		System.out.println("At time: "+ dataObject.getField("Time").toString() + " ~ Fire Alarm Activated!!!");
end
