package rules

import parser.DataObject;
import parser.DataObjectCollection;
import parser.ActionObject;
import java.util.HashMap;

rule "Creating_AO_1"
	when
		dataObjectCol : DataObjectCollection()		 	 
		dataObject : DataObject(name == "ChainRulingExample") from dataObjectCol.getCollection()
		eval(dataObject != null && dataObject.hasField("Data1") && dataObject.getField("Data1").equals("1"))
		
		dataObject2 : DataObject(name == "ChainRulingExample") from dataObjectCol.getCollection()
		eval(dataObject2 != null && dataObject2.hasField("Data2") && dataObject2.getField("Data2").equals("1"))
	then
	
		HashMap<String, String> hm = new HashMap<String,String>();
		hm.put("Action1", "1");
		//action objects take in a HM, a derived string, and string name.
		ActionObject dobj = new ActionObject(hm, "", "Action1");
		insert(dobj);
		System.out.println("Action Object 1 Created");
end
