package rules

import parser.DataObject;
import parser.ActionObject;
import parser.DataObjectCollection;
import java.util.HashMap;

rule "coolRuleFool"
	when
		dataObjectCol : DataObjectCollection()
		test1 : ActionObject()
		test2 : ActionObject()
		test1 : DataObject(name == "PoolLog") from dataObjectCol.getCollection() 
		 eval(test1 != null&&test1.getField("Temperature").equals("7"))
		test2 : DataObject(name == "PoolLog") from dataObjectCol.getCollection() 
		 eval(test2 != null&&test2.getFieldInt("Temperature")<89)
	then
		 System.out.println("hey");
end
