package rules

import parser.DataObject;
import parser.ActionObject;
import parser.DataObjectCollection;
import java.util.HashMap;

rule "myRule"
	when
		dataObjectCol : DataObjectCollection()
		heyThere : DataObject(name == "PoolLog") from dataObjectCol.getCollection() 
		 eval(heyThere != null&&heyThere.getField("Temperature").equals("62"))
		 eval(heyThere != null&&heyThere.getField("Water_Levels").equals("12"))
	then
		 System.out.println("hey");
end
