package cool

import parser.DataObject;
import parser.ActionObject;
import parser.DataObjectCollectionArrayList;
import java.util.HashMap;

rule "yes"
	when
		dataObjectCol : DataObjectCollectionArrayList()
		dataObject1 : DataObject(name == "PoolLog") from dataObjectCol.getCollection() 
		 eval(dataObject1 != null&&dataObject1.getFieldInt("Temperature")>20)
	then
		 System.out.println("ok");
end
