package rules

import parser.DataObject;
import parser.DataObjectCollection;
import parser.ActionObject;
import java.util.HashMap;

rule "Creating_Action_Object"

	when
		dataObjectCol : DataObjectCollection()		 
				 
		dataObject : DataObject(name == "FireAlarmSystem") from dataObjectCol.getCollection()
		eval(dataObject != null && dataObject.hasField("Current Temperature ( F )") && dataObject.getFieldInt("Current Temperature ( F )") >= 150)
		
		dataObject2 : DataObject(name == "PoolLog") from dataObjectCol.getCollection()
		eval(dataObject2 != null && dataObject2.hasField("Water_Levels") && dataObject2.getFieldInt("Water_Levels") >= 80)
	then

		HashMap<String, String> hm = new HashMap<String,String>();
		hm.put("FireExtinguishingMethod", "Pool Use");
		//action objects take in a HM, a derived string, and string name.
		ActionObject dobj = new ActionObject(hm, "FAS: Current Temp, PL: Water Level", "ExtinguishingMethod");
		insert(dobj);
		System.out.println("Action Object 1 Created");
end
