package rules

import parser.DataObject;
import parser.DataObjectCollection;
import driver.Prototype;

rule "Pool_Temp"

	when
		dataObjectCol : DataObjectCollection()
		pro : Prototype()		 
		 
		dataObject : DataObject(name == "PoolLog") from dataObjectCol.getCollection()
		eval(dataObject != null && dataObject.hasField("Temperature") && dataObject.getFieldInt("Temperature") < 120)

	then
		System.out.println("Temperature Check: Water Too Cold!");
end
