package rules

import parser.DataObject;
import parser.ActionObject;
import java.util.HashMap;

rule "Creating_AO_5"

	when
		action1 : ActionObject()
		action2: ActionObject()
		
		eval(action1 != null && action1.hasField("Action4") && action1.getField("Action4").equals("1")) && 
		eval(action2 != null && action2.hasField("Action3") && action2.getField("Action3").equals("1"))

	then
	
		HashMap<String, String> hm = new HashMap<String,String>();
		hm.put("Action5", "1");
		//action objects take in a HM, a derived string, and string name.
		ActionObject dobj = new ActionObject(hm, "", "Action5");
		insert(dobj);
		System.out.println("Action Object 5 Created");
end
