package rules

import parser.DataObject;
import parser.ActionObject;
import parser.DataObjectCollectionArrayList;
import java.util.HashMap;

rule "t"
	when
		dataObjectCol : DataObjectCollectionArrayList()
		dataObject1 : ActionObject(name == "Waterstuff") from dataObjectCol.getCollection() 
		 eval(dataObject1 != null&&dataObject1.getFieldInt("temp")<40)
	then
		 System.out.println("water temp is low!!");
end
