package rules

import parser.DataObject;
import parser.DataObjectCollectionArrayList;

rule "HIDE"
	when
		dataObjectCol : DataObjectCollectionArrayList()
		
		//dataObject : DataObject() from dataObjectCol.getObject("FireAlarmSystem")
		 
		dataObject : DataObject(name == "FireAlarmSystem") from dataObjectCol.getCollection()
		eval(dataObject != null && dataObject.hasField("Primary Power Supply") && dataObject.getFieldInt("Primary Power Supply") < 50)

	then
		System.out.println("Power is low");
end
